name: Setup Node
description: Setup Node, PNPM and Install dependencies
inputs:
  pnpm-version:
    description: PNPM version
    required: false
  node-version:
    description: Node.js version
    default: lts/*

runs:
  using: composite

  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Setup Node (${{ inputs.node-version }})
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
