name: Setup Repository
description: Setup Repository and Install dependencies

runs:
  using: composite

  steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure Git
      shell: bash
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

    - name: Setup ENV Vars
      shell: bash
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        echo "NODE_VERSION=$(cat .node-version)" >> $GITHUB_ENV

    - name: Setup Node Stuff
      uses: ./.github/actions/setup-node
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Setup Go Stuff
      uses: ./.github/actions/setup-go
      with:
        go-version: "1.21.5"

    - name: Install Additional Dependencies
      shell: bash
      run: |
        go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo@latest
