name: Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Bump Type"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Setup
        uses: ./.github/actions/setup

      - name: Build & Release
        run: pnpm release ${{ github.event.inputs.bump }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
